# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: Aven Deploy
description: Deploy an Aven project to a runtime server
author: Cameron Tacklind <cameron@tacklind.com>
inputs:
  deploy-key:
    required: true
    description: The key to use to auth with
  deploy-directory:
    required: false
    description: Folder to copy to remote
    default: '.'
  service-configs:
    required: false
    description: List of files to put into service config dir
    default: ''
  verbosity:
    required: false
    description: Control verbosity when running
    default: '1' # Some output
runs:
  using: node12
  main: main/index.js
