# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: Aven Deploy
description: Deploy an Aven project to a runtime server
author: Cameron Tacklind <cameron@tacklind.com>
inputs:
  domains:
    required: false
    description: |
      Whitespace separated list of domain names to use.
      The first one is the primary domain.
      All requests will be redirected to this domain by nginx.

  deploy-key:
    required: true
    description: The key to use to auth with

  extra-keys:
    required: false
    description: List of keys to add to authorized_keys on runtime server

  deploy-directory:
    required: false
    description: Folder to copy to remote
    default: '.' # Maybe dist?

  static-web-root:
    required: false
    description: Folder to serve statically with Nginx

  service-name:
    required: false
    description: What to call the Systemd service that runs this process
    # Uses the first domain name

  service-description:
    required: false
    description: Systemd service description

  start-server-command:
    required: false
    description: The command to run, with the code as the working directory.
    default: /usr/bin/npm start

  service-configs:
    required: false
    description: |
      Extra lines to put in Systemd config
      Use to extend the Aven Systemd service implementation
  service-config-files:
    required: false
    description: |
      List of files to put into service config dir.
      Use to extend the Aven Systemd service implementation

  runtime-user:
    required: false
    description: User to run the daemon as on the runtime server

  runtime-host-hostname:
    required: false
    description: Hostname of the runtime server that we're deploying to
  runtime-host-port:
    required: false
    description: Port of the runtime server that we're deploying to

  runtime-server-timezone:
    required: false
    description: |
      Set the runtime server's timezone.
      Must be one of "TZ database name".
      See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List

  apt-dependencies:
    required: false
    description: Apt dependencies to be installed for build or runtime

  runtime-apt-dependencies:
    required: false
    description: Apt dependencies to be installed for runtime only

  #journalbeat
  kibana-host:
    required: false
    description: Host to use for kibana.
  elastic-hosts:
    required: false
    description: Elastic Hosts
  elastic-username:
    required: false
    description: Elastic Username
  elastic-password:
    required: false
    description: Elastic Password
  logstash-hosts:
    required: false
    description: Hosts to use for elasticsearch.

  verbosity:
    required: false
    description: Control verbosity when running
    default: '1' # Some output
runs:
  using: node12
  main: main/index.js
