name: Main

on:
  pull_request:
  push:

jobs:
  publish:
    name: Build, Check, and Publish (release)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code (using self)
        uses: AvenCloud/actions/checkout@v1

      # - name: Checkout latest code (backup)
      #   uses: actions/checkout@v1
      # - name: Configure Npm
      #   run: echo "color = always" >> "${HOME}/.npmrc"
      # - name: Install Dependencies
      #   run: npm install

      - name: Check - Code Format
        if: always()
        run: npm run format-check -- --color

      - name: Check - Lint
        if: always()
        run: npm run lint -- --color

      - name: Check - Spelling
        if: always()
        run: npm run spell -- --color

      - name: Build
        if: always()
        run: npm run build

      - name: Publish to GitHub
        # Only publish if using release branch and all other steps succeed
        if: github.ref == 'refs/heads/release'
        uses: peaceiris/actions-gh-pages@v2
        env:
          PUBLISH_BRANCH: v1
          PUBLISH_DIR: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          emptyCommits: false
          username: 'GitHub Action Static Build'
          #useremail: "actions@github.com"
