name: Main

on:
  pull_request:
  push:

jobs:
  check-format:
    name: Check - Format

    runs-on: ubuntu-latest

    steps:
      # TODO: use self
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> "${HOME}/.npmrc"

      - name: Build
        run: npm install

      - name: Prettier
        run: npm run format-check -- --color

  check-lint:
    name: Check - Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> "${HOME}/.npmrc"

      - name: Build
        run: npm install

      - name: ESLint
        run: npm run lint -- --color

  check-spelling:
    name: Check - Spelling

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> "${HOME}/.npmrc"

      - name: Build
        run: npm install

      - name: cSpell
        run: npm run spell -- --color

  publish:
    name: Publish - Pre-compiled Action
    if: github.event_name == 'push' && github.ref == 'refs/heads/release'
    needs: [check-format, check-lint, check-spelling]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> "${HOME}/.npmrc"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to GitHub
        uses: peaceiris/actions-gh-pages@v2
        env:
          PUBLISH_BRANCH: v1
          PUBLISH_DIR: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          emptyCommits: false
          username: 'GitHub Action Static Build'
          #useremail: "actions@github.com"
